### ISSUE TITLE
homeassistant - is /mnt/includes necessary?

### ISSUE THREAD

**Issue by olevole** [tschettervictor/bsd-apps#3]
When installed the homeassistant in a classic container ( FreeBSD base on RO + {/var, /usr/local} in RW via nullfs overlay ), an error occurs:
```
mkdir: /mnt/includes: Read-only file system
```

I didn't find any reference to use /mnt/includes.

if it is necessary, it might make sense to put it in %%PREFIX%%,  **/usr/local**/mnt/includes ?

Thanks

**Comment by tschettervictor** [comment]
No. That is from a previous script. Removed.

Thanks.
